





spring:
  datasource:
    rtx:
      jdbc-url: jdbc:mysql://localhost:3306/rtx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
    titan:
      jdbc-url: jdbc:mysql://localhost:3307/titan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root